[
{"content":{"body":"While getting groceries I realized that `Response.error()` prolly exists for service workers. If they return one, do you get a rejected fetch?","format":"org.matrix.custom.html","formatted_body":"While getting groceries I realized that <code>Response.error()</code> prolly exists for service workers. If they return one, do you get a rejected fetch?","msgtype":"m.text","org.matrix.msc1767.message":[{"body":"While getting groceries I realized that `Response.error()` prolly exists for service workers. If they return one, do you get a rejected fetch?","mimetype":"text/plain"},{"body":"While getting groceries I realized that <code>Response.error()</code> prolly exists for service workers. If they return one, do you get a rejected fetch?","mimetype":"text/html"}]},"ts":1670516964804,"senderName":"annevk","senderId":"@annevk:matrix.org","id":"$fn-_akz0M5-OHPjGg9c9rFQOUlbxFraF20alsV0nQNU"},
{"content":{"body":"Jake Archibald: so based on `error_response` in WPT `service-workers/` it seems like there is some expectation that `Response.error()` is not turned into an exception similar to a network error. At least I think the cache test tries to store and retrieve it as-is.","format":"org.matrix.custom.html","formatted_body":"<a href=\"https://matrix.to/#/@jakea:matrix.org\">Jake Archibald</a>: so based on <code>error_response</code> in WPT <code>service-workers/</code> it seems like there is some expectation that <code>Response.error()</code> is not turned into an exception similar to a network error. At least I think the cache test tries to store and retrieve it as-is.","msgtype":"m.text","org.matrix.msc1767.message":[{"body":"Jake Archibald: so based on `error_response` in WPT `service-workers/` it seems like there is some expectation that `Response.error()` is not turned into an exception similar to a network error. At least I think the cache test tries to store and retrieve it as-is.","mimetype":"text/plain"},{"body":"<a href=\"https://matrix.to/#/@jakea:matrix.org\">Jake Archibald</a>: so based on <code>error_response</code> in WPT <code>service-workers/</code> it seems like there is some expectation that <code>Response.error()</code> is not turned into an exception similar to a network error. At least I think the cache test tries to store and retrieve it as-is.","mimetype":"text/html"}]},"ts":1670521586347,"senderName":"annevk","senderId":"@annevk:matrix.org","id":"$HkD2fpXqlKyTOSym7yGCHr9ia0Sm3oVOpy2W30_6h5Q"}
]