[
{"content":{"body":"Is there a particular reason why Array.from (https://tc39.es/ecma262/#sec-cma262/#sec-call) seems to call CloseIterator if an error occurs when setting `A`’s properties, when there are too many items, and when `mapfn` throws an error—but not when IteratorStep results in an abrupt completion nor when the iterator depletes its items?","format":"org.matrix.custom.html","formatted_body":"Is there a particular reason why Array.from (https://tc39.es/ecma262/#sec-cma262/#sec-call) seems to call CloseIterator if an error occurs when setting <code>A</code>’s properties, when there are too many items, and when <code>mapfn</code> throws an error—but not when IteratorStep results in an abrupt completion nor when the iterator depletes its items?","msgtype":"m.text"},"ts":1639624674110,"senderName":"jschoi","senderId":"@jschoi:matrix.org","id":"$nTIJ5p2Ya8bSZu74_xRZM8KojLMRT4xpTy2t7i3OT28"},
{"content":{"body":" * Is there a particular reason why Array.from (https://tc39.es/ecma262/#sec-cma262/#sec-call) seems to call CloseIterator if an error occurs when setting its result’s properties, if there are too many items, or if `mapfn` throws an error—but not when IteratorStep results in an abrupt completion nor when the iterator depletes its items?","format":"org.matrix.custom.html","formatted_body":" * Is there a particular reason why Array.from (https://tc39.es/ecma262/#sec-cma262/#sec-call) seems to call CloseIterator if an error occurs when setting its result’s properties, if there are too many items, or if <code>mapfn</code> throws an error—but not when IteratorStep results in an abrupt completion nor when the iterator depletes its items?","m.new_content":{"body":"Is there a particular reason why Array.from (https://tc39.es/ecma262/#sec-cma262/#sec-call) seems to call CloseIterator if an error occurs when setting its result’s properties, if there are too many items, or if `mapfn` throws an error—but not when IteratorStep results in an abrupt completion nor when the iterator depletes its items?","format":"org.matrix.custom.html","formatted_body":"Is there a particular reason why Array.from (https://tc39.es/ecma262/#sec-cma262/#sec-call) seems to call CloseIterator if an error occurs when setting its result’s properties, if there are too many items, or if <code>mapfn</code> throws an error—but not when IteratorStep results in an abrupt completion nor when the iterator depletes its items?","msgtype":"m.text"},"m.relates_to":{"event_id":"$nTIJ5p2Ya8bSZu74_xRZM8KojLMRT4xpTy2t7i3OT28","rel_type":"m.replace"},"msgtype":"m.text"},"ts":1639624681409,"senderName":"jschoi","senderId":"@jschoi:matrix.org","id":"$HsOtsqULKm9vsQW6ZtHj2OqHbdo4Ht9F613q9j2I0Pw"},
{"content":{"body":" * Is there a particular reason why Array.from (https://tc39.es/ecma262/#sec-cma262/#sec-call) seems to call CloseIterator if an error occurs when setting `A`’s properties, when there are too many items, and when `mapfn` throws an error—but not when IteratorStep results in an abrupt completion nor when the iterator depletes its items?","format":"org.matrix.custom.html","formatted_body":" * Is there a particular reason why Array.from (https://tc39.es/ecma262/#sec-cma262/#sec-call) seems to call CloseIterator if an error occurs when setting <code>A</code>’s properties, when there are too many items, and when <code>mapfn</code> throws an error—but not when IteratorStep results in an abrupt completion nor when the iterator depletes its items?","m.new_content":{"body":"Is there a particular reason why Array.from (https://tc39.es/ecma262/#sec-cma262/#sec-call) seems to call CloseIterator if an error occurs when setting `A`’s properties, when there are too many items, and when `mapfn` throws an error—but not when IteratorStep results in an abrupt completion nor when the iterator depletes its items?","format":"org.matrix.custom.html","formatted_body":"Is there a particular reason why Array.from (https://tc39.es/ecma262/#sec-cma262/#sec-call) seems to call CloseIterator if an error occurs when setting <code>A</code>’s properties, when there are too many items, and when <code>mapfn</code> throws an error—but not when IteratorStep results in an abrupt completion nor when the iterator depletes its items?","msgtype":"m.text"},"m.relates_to":{"event_id":"$nTIJ5p2Ya8bSZu74_xRZM8KojLMRT4xpTy2t7i3OT28","rel_type":"m.replace"},"msgtype":"m.text"},"ts":1639624736521,"senderName":"jschoi","senderId":"@jschoi:matrix.org","id":"$dyUYXPc05AKKvhzKCGTHdvzdH1xks6ty4mwGWrCHhG0"},
{"content":{"body":"we don't close the iterator when an error occurs in the iterator itself, because the iterator is broken","msgtype":"m.text"},"ts":1639627962311,"senderName":"bakkot","senderId":"@bakkot:matrix.org","id":"$p-E0Ozibd0wJxDv5B3rtPv7PgcIfb5RxtcZc0260Pnk"},
{"content":{"body":"and we don't close iterators when they are depleted in general","msgtype":"m.text"},"ts":1639627972044,"senderName":"bakkot","senderId":"@bakkot:matrix.org","id":"$qbU3oFW3eX3RkYtDqCK7u4hclEdHs_gewxpthpQVYpM"},
{"content":{"body":"(the assumption is that it does its own cleanup before returning `{done: true}`)","format":"org.matrix.custom.html","formatted_body":"(the assumption is that it does its own cleanup before returning <code>{done: true}</code>)","msgtype":"m.text"},"ts":1639627994185,"senderName":"bakkot","senderId":"@bakkot:matrix.org","id":"$SAHHsQW_ihFhOc63qE1pmKnQoIiniXYHKJRWyCmzrmQ"},
{"content":{"body":"we only cause IteratorClose when we need to close an iterator because we can no longer consume it for reasons of our own","msgtype":"m.text"},"ts":1639628030399,"senderName":"bakkot","senderId":"@bakkot:matrix.org","id":"$cK8VBbVzZKtsBXqDjzKDqwAkAaYC2NJr3P2Q3zJzHLE"}
]