[
{"content":{"body":"> <@legendecas:matrix.org> https://docs.google.com/document/d/1oPJj7k0txm0p54lKQ0ngS8ifEU1WGDhyKLbZmpfckJg/edit\n\nThis is a good writeup. It should probably also speak to the issue Andreu raised above: when you call .then(cb) and get a new promise, or when you do an await inside of an async function with no catch, the *resulting* promise is the one which has the unhandled rejection, and its rejection site is the one that is used. In those two cases, the rejection site is the place is the same as the creation site.","format":"org.matrix.custom.html","formatted_body":"<mx-reply><blockquote><a href=\"https://matrix.to/#/!eQuZUAhGqudVFPodUG%3Amatrix.org/%24swXmMbC3lc32dm4pytPjTZm72Q-oj1jQRou2AnMXZV8\">In reply to</a> <a href=\"https://matrix.to/#/@legendecas:matrix.org\">@legendecas:matrix.org</a><br>https://docs.google.com/document/d/1oPJj7k0txm0p54lKQ0ngS8ifEU1WGDhyKLbZmpfckJg/edit</blockquote></mx-reply>This is a good writeup. It should probably also speak to the issue Andreu raised above: when you call .then(cb) and get a new promise, or when you do an await inside of an async function with no catch, the <em>resulting</em> promise is the one which has the unhandled rejection, and its rejection site is the one that is used. In those two cases, the rejection site is the place is the same as the creation site.","m.relates_to":{"m.in_reply_to":{"event_id":"$swXmMbC3lc32dm4pytPjTZm72Q-oj1jQRou2AnMXZV8"}},"msgtype":"m.text"},"ts":1693958529064,"senderName":"littledan","senderId":"@littledan:matrix.org","id":"$uscJMcELGb-UzBluPuKy3m7mv9smAgFRhC8WycYH8RA"}
]