[
{"content":{"body":"I was thinking that the unhandled rejection context here is `\"foo\"`, not `\"baz\"`:\n```js\nasyncVar.run(\"foo\", main);\n\nasync function main() {\n\tawait asyncVar.run(\"bar\", async () => {\n\t\tawait asyncVar.run(\"baz\", async () => {\n\t\t\tthrow new Error();\n\t\t});\n\t});\n}\n```","format":"org.matrix.custom.html","formatted_body":"<p>I was thinking that the unhandled rejection context here is <code>\"foo\"</code>, not <code>\"baz\"</code>:</p>\n<pre><code class=\"language-js\">asyncVar.run(\"foo\", main);\n\nasync function main() {\n\tawait asyncVar.run(\"bar\", async () =&gt; {\n\t\tawait asyncVar.run(\"baz\", async () =&gt; {\n\t\t\tthrow new Error();\n\t\t});\n\t});\n}\n</code></pre>\n","m.mentions":{},"msgtype":"m.text"},"ts":1719839472632,"senderName":"Andreu Botella","senderId":"@abotella:igalia.com","id":"$-U5pW_mwO2UMMP1Vk6MyBngnvYdRIqW2mImf9P0EW7c"},
{"content":{"body":"so shouldn't it be the same for sync errors?","m.mentions":{},"msgtype":"m.text"},"ts":1719839485492,"senderName":"Andreu Botella","senderId":"@abotella:igalia.com","id":"$YgrG3oIZyR2lNxI06x1Y3mp4fX58uz_zhgq0hl3Qz3s"},
{"content":{"body":" * so shouldn't it be the same for sync unhandled errors?","m.mentions":{},"m.new_content":{"body":"so shouldn't it be the same for sync unhandled errors?","m.mentions":{},"msgtype":"m.text"},"m.relates_to":{"event_id":"$YgrG3oIZyR2lNxI06x1Y3mp4fX58uz_zhgq0hl3Qz3s","rel_type":"m.replace"},"msgtype":"m.text"},"ts":1719839490581,"senderName":"Andreu Botella","senderId":"@abotella:igalia.com","id":"$1ZWcRD_ilkZoYR-RBTETe7ukTcR5vDtONh6-GvvRW3E"},
{"content":{"body":"I don't understand what you're getting at; the async/await case is different since it corresponds to a bunch of nested try/catch/rethrow patterns.","m.mentions":{},"msgtype":"m.text"},"ts":1719840540985,"senderName":"littledan","senderId":"@littledan:matrix.org","id":"$G5EfVaC1XLBqkfF1xcEY57jWqk6UAxR6VmxS69ih66s"}
]